#!/usr/bin/env bash
set -e

# Install from source until 0.4.9 release
pip uninstall -y spikeinterface
git clone https://github.com/alejoe91/spikeinterface.git
cd spikeinterface
git checkout 7c27eede08096f5ccb81a709f02a7bb69d8d99a6
pip install --ignore-installed --no-cache-dir .
cd ..